export const SAVE_EMAIL = 'SAVE_EMAIL';
export const SAVE_EXPENSE = 'SAVE_EXPENSE';

export const SELECTED_EXPENSE = 'SELECTED_EXPENSE';

export const ATT_EXPENSES = 'ATT_EXPENSES';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const REQUEST_REALIZED = 'REQUEST_REALIZED';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const GET_CURRENCY = 'GET_CURRENCY';
